---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-system
        namespace: flux-system
      version: 4.0.18
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: nfs-values