cloudflare:
    tunnelName: jstuart.ca
    secretName: tunnel-credentials
    ingress:
      - hostname: jstuart.ca
        service: http://personal-site.homepage:80
      - hostname: www.jstuart.ca
        service: http://personal-site.homepage:80
      - hostname: quartz.jstuart.ca
        service: http://quartz-blog.homepage:80
      - hostname: blog.jstuart.ca
        service: http://nginx-nginx-ingress-controller.nginx-system:80
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
replicaCount: 1
