cloudflare:
    tunnelName: jstuart.ca
    secretName: tunnel-credentials
    ingress:
      - hostname: blog.jstuart.ca
        service: http://httpbin.default:80
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
replicaCount: 1
