---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole-system
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      version: 2.34.0
  interval: 30m
  valuesFrom:
  - kind: ConfigMap
    name: pihole-values