---
nodeSelector:
  kubernetes.io/hostname: "tp2-node2"
# DNS servers that pi-hole will use
DNS1: 9.9.9.9
DNS2: 1.1.1.1
persistentVolumeClaim:
  enabled: true
admin:
  # admin access secret
  existingSecret: "pihole-admin"
serviceDns:
  mixedService: true
  loadBalancerIP: 10.20.1.12
  type: LoadBalancer
# Don't need DHCP
serviceDhcp:
  enabled: false
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 9.9.9.9