---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quartz-blog
  namespace: homepage
spec:
  chart:
    spec:
      chart: quartz-blog
      sourceRef:
        kind: HelmRepository
        name: jstuart
        namespace: flux-system
      version: 0.1.0
  interval: 30m
