---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-blog
  namespace: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-ghost
    namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: ghost-values