---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost-secrets.yaml
  - helmrelease.yaml
  - ghost-content-backup.yaml
configMapGenerator:
  - name: ghost-values
    files:
    - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml