ghostHost: blog.jstuart.ca
ghostUsername: jgpstuart@gmail.com
ghostEmail: jgpstuart@gmail.com
existingSecret: "ghost-credentials"
ghostBlogTitle: Hot Ginger&Dynamite
ghostEnableHttps: true
allowEmptyPassword: false
resourcesPreset: "2xlarge"
service:
  type: NodePort
ingress:
  enabled: true
  hostname: blog.jstuart.ca
  ingressClassName: "nginx"
  annotations: "nginx.ingress.kubernetes.io/server-snippet:"
persistence:
  enabled: true
  size: 50G
mysql:
  auth:
    existingSecret: "ghost-mysql-password"