ghostUsername: jgpstuart@gmail.com
existingSecret: "ghost-credentials"
ghostBlogTitle: Hot Ginger&Dynamite
ghostEnableHttps: false
allowEmptyPassword: true
resourcesPreset: "2xlarge"
service:
  type: NodePort
ingress:
  enabled: false
  hostname: blog.jstuart.ca
persistence:
  enabled: true
  size: 50G
mysql:
  auth:
    existingSecret: "ghost-mysql-password"