apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jstuart
    namespace: flux-system
spec:
    interval: 30m
    url: https://helm.jstuart.ca/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb0JGSDBocitYa0Z4R0hS
            cDg0WUpCQ2MzTGRRaThJb0FzRTRpMkVpK0JZCndSQmdyMWN2VDV4N3l1T0ZrWnFl
            cXZTTjkybHhFSEI5bE5DOFZyNTR2OUUKLS0tIG45eGJ1cFZvQ0tNSGlRZDVaK2Q5
            TVdpaWFoR29Dd1dOdmtDR29ER0NhM0kK3twF9wK8A08JfyfxEmc+OZii3Sr5flDW
            mOGQrEMbrWmhrDkry6cNUmlRHu8wsPq7dGp5T8q3C1lpXe9MZ+/uqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:10:09Z"
    mac: ENC[AES256_GCM,data:krEAkvZFP9TsGPb+XWnZVJCCLWyMNl5OSeijoemjDZhcp4eNjZNxuOoMno1wUnwMgYZsE9dcll8JE4o4Mo30RSH8eilSZLDxu4gd9VfoKNek1a0GjMcRG7N2psW9JaC5KZmmhFf81UkFbHOE1CsNfWGSrdJ+SVD11pB01e+e1N8=,iv:F/hY4CUvyyrYWWVd2UIAgW6gP2qFSRM/IAQ3msa4kjk=,tag:6d39nIR9mpobjhAOxxyRHg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-login-secret
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:XqC5MA4VRXyF8G+BnyepSH187o8Q9G+v9S5tVsuSMKdJjCJpBOyaVmvMPngn9zv5luIxmQxx0KlFxLXdNdy4HchNaKxR7uBR5Q6/KKb6/j5eeiyGYHjZlX9vDr3dcnm/ofYo/+Q=,iv:5+jcFeEIbWWNV2LEUpuqgk9GCooQs/MvTE3KQXISTP8=,tag:ZvLtjOGRWO/Trfa1nSaYtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb0JGSDBocitYa0Z4R0hS
            cDg0WUpCQ2MzTGRRaThJb0FzRTRpMkVpK0JZCndSQmdyMWN2VDV4N3l1T0ZrWnFl
            cXZTTjkybHhFSEI5bE5DOFZyNTR2OUUKLS0tIG45eGJ1cFZvQ0tNSGlRZDVaK2Q5
            TVdpaWFoR29Dd1dOdmtDR29ER0NhM0kK3twF9wK8A08JfyfxEmc+OZii3Sr5flDW
            mOGQrEMbrWmhrDkry6cNUmlRHu8wsPq7dGp5T8q3C1lpXe9MZ+/uqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:10:09Z"
    mac: ENC[AES256_GCM,data:krEAkvZFP9TsGPb+XWnZVJCCLWyMNl5OSeijoemjDZhcp4eNjZNxuOoMno1wUnwMgYZsE9dcll8JE4o4Mo30RSH8eilSZLDxu4gd9VfoKNek1a0GjMcRG7N2psW9JaC5KZmmhFf81UkFbHOE1CsNfWGSrdJ+SVD11pB01e+e1N8=,iv:F/hY4CUvyyrYWWVd2UIAgW6gP2qFSRM/IAQ3msa4kjk=,tag:6d39nIR9mpobjhAOxxyRHg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
