apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jstuart
    namespace: flux-system
spec:
    interval: 30m
    url: https://helm.jstuart.ca/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa3g3WWErblRzblBDVERT
            cHRvcy9MOWVVMkx1YmVaVSsyNjVJN2RkcVdBCnJyUjZQMFNuYWJFUGJMSlg5bm5P
            MlEySTBXK0FINEp6S29lZ0IzTEZhQUkKLS0tIE1OSjVqdGpHbjZTUzB0a2NDVHlY
            LzYxMTkxdjcxQlYvSWwyRlFSTytrek0K8ES4UmCfoFG4t+EVA8yAaDKQq76pbXId
            do05FWMsVy1zqAXo9y6Tf7Fpn6bl6zjRHbnYEL325qj/WIbDvZpN8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T13:49:39Z"
    mac: ENC[AES256_GCM,data:86uGID9C/83pBfdTulucTw19V7scLgVGOvaOgI7XfUTU4cK8snAw/v8vizbOUY3mDF0p+2cvx0O4g6ajdyGI0U0Dh2EaG+ddLApybSfcxAPuPNUgH26kMsE3GGCQ69el+3ucPKWP8dx07dySjzYnTpk2Ub5sH2wVudq6Fk3msxY=,iv:pYtaOX/5MrwP4vxD/vi+1YpDDysSor6RUOs965jcJaY=,tag:rUZSJrIMkM6nRtQV2lYP+g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-login-secret
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JhT7YmcK3BDVlBgpaL0noWs9vw79ii4uiGO+/6Y+26NebKQ8QErInycgFf9U5gX6vSaY3b0UKuLCTbGOCnnQVGT2S54JewyQkyXqFEH2bl2UUJVmicuvC5ae3rwbik+GgnY0jG+fuknlHvxG8zMjaFs+4ivEVA==,iv:koEV/e2OsQ3AHBTZtLirNt4soJ18uF0iXDyewtQgNyY=,tag:nb8QkkE7vpw9wyEOf31GAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa3g3WWErblRzblBDVERT
            cHRvcy9MOWVVMkx1YmVaVSsyNjVJN2RkcVdBCnJyUjZQMFNuYWJFUGJMSlg5bm5P
            MlEySTBXK0FINEp6S29lZ0IzTEZhQUkKLS0tIE1OSjVqdGpHbjZTUzB0a2NDVHlY
            LzYxMTkxdjcxQlYvSWwyRlFSTytrek0K8ES4UmCfoFG4t+EVA8yAaDKQq76pbXId
            do05FWMsVy1zqAXo9y6Tf7Fpn6bl6zjRHbnYEL325qj/WIbDvZpN8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T13:49:39Z"
    mac: ENC[AES256_GCM,data:86uGID9C/83pBfdTulucTw19V7scLgVGOvaOgI7XfUTU4cK8snAw/v8vizbOUY3mDF0p+2cvx0O4g6ajdyGI0U0Dh2EaG+ddLApybSfcxAPuPNUgH26kMsE3GGCQ69el+3ucPKWP8dx07dySjzYnTpk2Ub5sH2wVudq6Fk3msxY=,iv:pYtaOX/5MrwP4vxD/vi+1YpDDysSor6RUOs965jcJaY=,tag:rUZSJrIMkM6nRtQV2lYP+g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
