apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jstuart
    namespace: flux-system
spec:
    interval: 30m
    url: https://helm.jstuart.ca/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcCthb29pTWtVTmFXaHlI
            cTdtUGlCekxqeXp3RFFyV3JPYUtWVDdqUkJBCmJjMmRiRW03aXZMT0gvaDVhK2V4
            SnJMdnZPeW4zRUdlY25pVVUwd0ZPMGMKLS0tIENBZTV0bVVHYWdoaXpwc0V6eVRS
            aFVIVUpKWmVhYnNHenF1czVlVXVMNXMK5qqpjHSM1F2yX4QzCZvA1b3QD7ypSvEv
            Gx9QgAyTmW68k4Shx0bRuII4z3RuOPOG21kaFVJEtp1WoikfURU6Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:40:35Z"
    mac: ENC[AES256_GCM,data:CeAYnXDrOybvOFqFUyrrKZ4+NmF+ajNbxf4EWj1V1rqhGOY/0TE3HMP6zz/7v1NRKUR2R2LkVB3QTraII4xPkNURY/xE9TiS9fA5h0k6MdzW673eGkXdqxt3Ju2+Naq8aZZI8hyvdKsCQu3EH5XP07Xr2WVPhM1j2fyXy+eA/Kw=,iv:4PBDZvp6r29NXVnLP8hMVxM5+xF2M+/QgHgywcS1QQI=,tag:47cX28Md9CwrVOEDQfjaYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-login-secret
    namespace: homepage
data:
    .dockerconfigjson: ENC[AES256_GCM,data:1R7dZL3XoEO+KNTaTSvBaNAXh2ohMT19jG3hNxyXU+cIE5sF+z0IRthUH+vdaym8O9XBTtYq/rOemNK/xE2YIxOq70RttrBg1e0KiAb18JQWiGiw03/6mGi32Z9hbdCIi449R3XDeUgqiKpa6J/dkXkVqCek6sBn+gEiKu2xl08tx7zvs9BTIg==,iv:oe7Q7cTS1h4t7LIUrYqAWs6WUx5KfCoeQjjPcjKIbTg=,tag:CT6aidM8y7dDj/II+xrEfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcCthb29pTWtVTmFXaHlI
            cTdtUGlCekxqeXp3RFFyV3JPYUtWVDdqUkJBCmJjMmRiRW03aXZMT0gvaDVhK2V4
            SnJMdnZPeW4zRUdlY25pVVUwd0ZPMGMKLS0tIENBZTV0bVVHYWdoaXpwc0V6eVRS
            aFVIVUpKWmVhYnNHenF1czVlVXVMNXMK5qqpjHSM1F2yX4QzCZvA1b3QD7ypSvEv
            Gx9QgAyTmW68k4Shx0bRuII4z3RuOPOG21kaFVJEtp1WoikfURU6Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:40:35Z"
    mac: ENC[AES256_GCM,data:CeAYnXDrOybvOFqFUyrrKZ4+NmF+ajNbxf4EWj1V1rqhGOY/0TE3HMP6zz/7v1NRKUR2R2LkVB3QTraII4xPkNURY/xE9TiS9fA5h0k6MdzW673eGkXdqxt3Ju2+Naq8aZZI8hyvdKsCQu3EH5XP07Xr2WVPhM1j2fyXy+eA/Kw=,iv:4PBDZvp6r29NXVnLP8hMVxM5+xF2M+/QgHgywcS1QQI=,tag:47cX28Md9CwrVOEDQfjaYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
