apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jstuart
    namespace: flux-system
spec:
    interval: 30m
    url: https://helm.jstuart.ca/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TlJsQjdKN0pwS05mRGx5
            Vi96dERoM0xVRHdXOTF6bU5qcVB5NUhBZ0RFCnI4SWVxKzN0cTlDMTdlRzJVcjZs
            NUswWDIxVzJrMExab2dTNVNaK21UekEKLS0tIGt2TWxSTlR3K3M0Nzk2ZHJxTjRn
            a0JYb1Z2dzZlTm50MFlCdHVyRU16cHcKdePN/yDQbnWR2aST5lrQdU+ISOjiaxDR
            hBl145yoEYn+sShwz+ubYTILJ21SWaAc7DCJD6LDOXCvHjyI1Op8ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T16:46:10Z"
    mac: ENC[AES256_GCM,data:NkT9ZK3uX7w3cIh4/wIJcunnWDwXtYsMqpNEREMcJ1AwAeyixD6Zvqp25hJwsLUH/93ICKC+ew+cfMUE6B2Sc36j7IYtWRwB7lN3kEfHN6EKiwVsugs+hbfszuVw8v4vrEMM6HsaE+ONV/FZJK97xmOy0RoPdieTc0h1h7EMvwI=,iv:QqaHopCEwQg6Zdt6SexStoieMU6qcWwZWEX6BGPeUV0=,tag:PtaXrFk3PYirxLbdJEJzKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TlJsQjdKN0pwS05mRGx5
            Vi96dERoM0xVRHdXOTF6bU5qcVB5NUhBZ0RFCnI4SWVxKzN0cTlDMTdlRzJVcjZs
            NUswWDIxVzJrMExab2dTNVNaK21UekEKLS0tIGt2TWxSTlR3K3M0Nzk2ZHJxTjRn
            a0JYb1Z2dzZlTm50MFlCdHVyRU16cHcKdePN/yDQbnWR2aST5lrQdU+ISOjiaxDR
            hBl145yoEYn+sShwz+ubYTILJ21SWaAc7DCJD6LDOXCvHjyI1Op8ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T16:46:10Z"
    mac: ENC[AES256_GCM,data:NkT9ZK3uX7w3cIh4/wIJcunnWDwXtYsMqpNEREMcJ1AwAeyixD6Zvqp25hJwsLUH/93ICKC+ew+cfMUE6B2Sc36j7IYtWRwB7lN3kEfHN6EKiwVsugs+hbfszuVw8v4vrEMM6HsaE+ONV/FZJK97xmOy0RoPdieTc0h1h7EMvwI=,iv:QqaHopCEwQg6Zdt6SexStoieMU6qcWwZWEX6BGPeUV0=,tag:PtaXrFk3PYirxLbdJEJzKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
apiVersion: v1
kind: Namespace
metadata:
    name: homepage
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TlJsQjdKN0pwS05mRGx5
            Vi96dERoM0xVRHdXOTF6bU5qcVB5NUhBZ0RFCnI4SWVxKzN0cTlDMTdlRzJVcjZs
            NUswWDIxVzJrMExab2dTNVNaK21UekEKLS0tIGt2TWxSTlR3K3M0Nzk2ZHJxTjRn
            a0JYb1Z2dzZlTm50MFlCdHVyRU16cHcKdePN/yDQbnWR2aST5lrQdU+ISOjiaxDR
            hBl145yoEYn+sShwz+ubYTILJ21SWaAc7DCJD6LDOXCvHjyI1Op8ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T16:46:10Z"
    mac: ENC[AES256_GCM,data:NkT9ZK3uX7w3cIh4/wIJcunnWDwXtYsMqpNEREMcJ1AwAeyixD6Zvqp25hJwsLUH/93ICKC+ew+cfMUE6B2Sc36j7IYtWRwB7lN3kEfHN6EKiwVsugs+hbfszuVw8v4vrEMM6HsaE+ONV/FZJK97xmOy0RoPdieTc0h1h7EMvwI=,iv:QqaHopCEwQg6Zdt6SexStoieMU6qcWwZWEX6BGPeUV0=,tag:PtaXrFk3PYirxLbdJEJzKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-login-secret
    namespace: homepage
data:
    .dockerconfigjson: ENC[AES256_GCM,data:c2BiW7uCaqOP4ElOdDi0bpN7ksI/fdS1X6w0D2YCe0CFCPXaurFkU27L6gRnhRg4V3amisp/8TdsiJ0VhaMN/HfZpXA5K7qbwyPsX4Bq/nOHtUhm7I3pK2ENQM2Lv7b5VXV29MFV+wsCwvfTApOjinGMWHX9tlixLCMy13g0tnxNjeccQfp8Bg==,iv:DnR6oKXULNwh/tjU80ftw/3FYgJhrofY2T2ozd3QKEY=,tag:4T8bsr94++P5k6dNmF+i9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TlJsQjdKN0pwS05mRGx5
            Vi96dERoM0xVRHdXOTF6bU5qcVB5NUhBZ0RFCnI4SWVxKzN0cTlDMTdlRzJVcjZs
            NUswWDIxVzJrMExab2dTNVNaK21UekEKLS0tIGt2TWxSTlR3K3M0Nzk2ZHJxTjRn
            a0JYb1Z2dzZlTm50MFlCdHVyRU16cHcKdePN/yDQbnWR2aST5lrQdU+ISOjiaxDR
            hBl145yoEYn+sShwz+ubYTILJ21SWaAc7DCJD6LDOXCvHjyI1Op8ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T16:46:10Z"
    mac: ENC[AES256_GCM,data:NkT9ZK3uX7w3cIh4/wIJcunnWDwXtYsMqpNEREMcJ1AwAeyixD6Zvqp25hJwsLUH/93ICKC+ew+cfMUE6B2Sc36j7IYtWRwB7lN3kEfHN6EKiwVsugs+hbfszuVw8v4vrEMM6HsaE+ONV/FZJK97xmOy0RoPdieTc0h1h7EMvwI=,iv:QqaHopCEwQg6Zdt6SexStoieMU6qcWwZWEX6BGPeUV0=,tag:PtaXrFk3PYirxLbdJEJzKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
