---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-system
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner