---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: arc-runner-set-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: arc-runner-set-secret-quartz
    files:
      - secret.yaml
configurations:
  - kustomizeconfig.yaml