---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runner-auth-secret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: arc-runner-set-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml