apiVersion: v1
kind: Secret
metadata:
    name: arc-runner-set-secret-quartz
    namespace: arc-system
type: Opaque
stringData:
    github_app_id: "982619"
    github_app_installation_id: "54290711"
    github_app_private_key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA0Cmg4N26H6+d1bF39IwzN/x64joDSGe+jmaGSHNJm6B8x3t8
        0CczjX0M+YEpUs9V+C24SJucvwFpuY7aoyhy8VxwaS14aNHTTcT5PW4UXiLEzwo8
        K+OQ9yU2cqzOQJVG7JORDXOB17xY5O0N22AklF5R1DgYUkU7G6TvTdOXG+IzrzZY
        9/3VGPmORa6c65suZpj5l9P0CXJzuTHKSarGl+40R/7PBQFGJoUfO9VOZ2v6HUlr
        A0n9zIqR/VGpqrCsbinXO+oYYG64sJF8AwiwWc0ABwTqqKlpXb3G4qs97ksNsbAC
        FXN28BPklDUc7Ri7tjvYCcadxIpwR7qwhVLHWQIDAQABAoIBADgFC/OYGC/QzjQl
        F3grhtkpTFS3cgy5RrIB619yDzwfm5T/qZ5G/nu0TJqU5O8RNzyb6T05C5znn3E9
        fZ9tEkncK7BSeVYUKb6DJOQgTMDssHRbd8gD7Q5l6FpCIRuGUNj3+ZBaJnZNjMrG
        9PS10gJPw8vN8NWrJfYRlAkoyUDKSdDNrgmK1XzOohGac2/o/PhlcP631baRHAtd
        25uQ4smj1ACN9NmxX40NlSX5GNEoQWmp4nfrUIb9mP846C/Oykk2o22ApR8oO7SC
        9I5XnKY0JjthdJGSSWykNqa5YYMSo5iePsbdrNu3BtHs+8wSo4IWc9MYj2aRIvrS
        iP6fdoUCgYEA9OraOJan1v1Hj06FF+/LVH8xX385MteaYW/PdW/Z5c8osygLQM5T
        W3N7+wXKPAwn0g9Ms+kW7DTXfsYrf7VWUBkjZI0ihYlLnH8Lossk9zh1hfN3dl/c
        kCLVCyzF0MBouIhwPCo6WnzsJXyJB4nW+kHwz5M20vmF3uwWGmb0nS8CgYEA2ZUB
        Q+jZaRLw58+LGlKXL8TLi8+j77WR1tsHR5P6NiOVIZxnMK81S0pD0oq/tpMphx05
        OeKCQXkSOH4OUw3pnyxia3s0+mhICcNft37sWFyfp0Dx//2DZyw5qg+vZgCUrrql
        x0RhvhFpz4ng7ATybFBIN+tFTw0j3lw+vNtREfcCgYEAvoNNOoWei3K7znLSvvrt
        3I2QN2u8b5sc4Lxb0UsvYT8StsHodwHH/7RGdc5cMPd3pkP2c2BWT2kPU/MM9St2
        t5nGWTob52oUIekFgR2qZJBLguYPQEpzRL+Dn0y1l5uEGj8vpu1mNOtFuic0ZGPJ
        kSPoEV+/Xr9wbiaRTvpVP0sCgYA8/4YESNIyn+nDwy6HKaJS9QPvZT3bZPbG2k63
        JWgfJ2iWrKdNQcFaIy7SZq2KfMVGqM2zSaokutF93vEbHapiQmoxIbBfhz6y5f/+
        jGmr+AOWOyHdF3BwSzi7UXxlx0HnnlH9hFE2nOEiGtBgup5P+U3Vx3J9z/w/SXMZ
        NQ8MTwKBgQDAxAc7Ean5ycQPq6yckUjpfZbL42+I5Da8rUGSDjUF1eeLUFaOYL/U
        UQ8LHpiN8OjzgxgvKaBn86cviSpwg4Cq0q7/DWfVe7YPmGBpOuHyGmVPo6kPw0Hp
        oQ4SyTpOWCNFwicLonRt+rO1wKoXTnOThV4ReeEsYJn8PBVF4ABHIA==
        -----END RSA PRIVATE KEY-----
sops:
    age:
        - recipient: age1ls9x0qp4pwlca3mshmh5js355nvk4wrktc3538agvrdv645duvgqr7708h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UUh4WHlMVEJJbFhrQXF4
            ZGNkcW9GMGdud2NJSnE5YVc5M3BTV2FHTjFJCmlKYklrN3cxRUVpQ0VsR241VFMr
            MnVHcVEvT2lDblFDbDVuazk4bm91WFEKLS0tIFA4YzhJNjRnRTlyRnJrRTRrcDFO
            VTRTa0IwMWJjZGpmSFkxa0pxYWJwR1EKGnLTXPGa1lW941zU7B8mwdJCvN1wP+Pp
            gcmXtqJjT2fgzUOBcd9JDHD1fXlWWdyUuCSbP2awBzUJBu793S3Ieg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T20:24:48Z"
    mac: ENC[AES256_GCM,data:IU7AHv1EJ9qvygxo9S70NRowpqRv1Bn8pMRijequWSeDZqESnCkMT3Cxq0Z3j2LkTe06Y++skTUyhxrAAa+xoSActnVEUWm+vYPy6J93KcF1yCtJ8Cw9iVA0vM8lOZ/AIMCvXOjrOdeF9CzDeybuh9j/Lg09zVi8z/m9oQpbjFA=,iv:X9kHXIyqgy58lyupF6Ldsy7n2vgdfdj+4Pwr39QlxIY=,tag:yZm4GAKMKkLmsI/woHLHnQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.0
