---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arc-runner-quartz
  namespace: flux-system
spec:
  targetNamespace: arc-system
  path: ./clusters/turingpi2/apps/arc/quartz-blog-runner/gha-runner-scale-set/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age