---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  targetNamespace: uptime-kuma-system
  path: ./clusters/turingpi2/system/uptime-kuma-system/uptime-kuma/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m